spring.application.name=NOTIFICATION-SERVICE
# Server Configuration
server.port=8085

spring.kafka.bootstrap-servers=http://localhost:9092

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
