spring.application.name=PATIENT-SERVICE
server.port=8001

spring.datasource.url=jdbc:postgresql://localhost:5434/patientdb
spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# management.endpoint.health.show-details=always
# management.endpoints.web.exposure.include=always

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka